### ISSUE TITLE
[BUG] Speed calculation goes wrong after passing a CP (and stage?)

### ISSUE THREAD

**Issue by breakthegreat** [olokos/Surftimer-olokos#57] opened 2020-04-25 01:17 UTC
**Describe the bug**
The speed calculation on the timer hud goes all the way down to 300 when passing a checkpoint (when I have more than 2000+ u/s). I believe it does the same in staged map (where you can keep up your speed inbetween stages ex: kistune or ace_fix).
**Expected behavior**
~~Timer should show real speed~~ Real speed is shown, just not entirely. (missing the 4th number when we're over 1000 u/s) 

**Screenshots**
![image](https://user-images.githubusercontent.com/64219376/80267787-da96da80-8670-11ea-96cf-fce92e6e0010.png)

**Additional context**
That issue that came around with 285. Seems like the speed is back at 200/300 for a good 2 or 3 second before growing again, ~~I believe the timer goes back to 0 u/s once we pass the stage and it simply adds the units we gained after we passed the stage (so there is a complete loss of the previous unit count as soon as we pass the checkpoint)~~

**update**
It appears the units are stuck at 200/300 as soon as the checkpoint time  PR and SR are displayed on the HUD. Once the CP time disappears from the timer central HUD, the units are back to normal.
Tested on multiple maps.

**update 2**
I believe the timer is missing the 4th number 
Ex your speed is: 3000u/s, you pass the CP: it now shows : 300u/s
Speed is: 2580 u/s, you pass the CP: it now shows: 258u/s
Hope this will help.

**Comment by sneak-it** [comment] 2020-04-25 01:34
Duplicate of #5

**Closed by sneak-it** 2020-04-25 01:34 UTC
Labels: bug
