### ISSUE TITLE
[BUG] showing {default} on tab menu

### ISSUE THREAD

**Issue by Caaine** [olokos/Surftimer-olokos#89] opened 2020-05-02 11:26 UTC
**Describe the bug**
showing {default} on tab menu

**Screenshots**
https://cdn.discordapp.com/attachments/671755264428474368/706102599018872832/unknown.png

**Additional context**
dev branch
sm 1.10
ubuntu 18.04

**Comment by sneak-it** [comment] 2020-05-02 15:59
Image link does not work

**Comment by Caaine** [comment] 2020-05-02 16:14
https://steamuserimages-a.akamaihd.net/ugc/1009313639770550170/ABAE3ADCEBF4E847A88D73027EA260240B6445DE/

**Comment by olokos** [comment] 2020-05-02 16:40
This works @Caaine 
and I think I can confirm the issue, but this might be due to not building the colorlib.inc manually, just using precompiled version

I am not entirely sure about this, but this also happens on my server running dev branch. 😢

**Comment by covertxd** [comment] 2020-05-02 18:55
I am also having this issue with the color tags not being removed for the scoreboard.

**Comment by Bara** [comment] 2020-05-02 20:06
Try this version.
[SurfTimer.zip](https://github.com/olokos/Surftimer-olokos/files/4568683/SurfTimer.zip)

**Comment by Bara** [comment] 2020-05-02 20:16
[SurfTimer.zip](https://github.com/olokos/Surftimer-olokos/files/4568711/SurfTimer.zip)
Compiled with threadedSQL branch.

**Comment by Caaine** [comment] 2020-05-02 21:27
working

**Comment by KristianP26** [comment] 2020-05-03 18:21
![image](https://user-images.githubusercontent.com/28766334/80922179-88923b00-8d7b-11ea-9dff-58a503af1652.png)
Problem is not only in Tab menu

**Comment by Bara** [comment] 2020-05-03 18:36
Normally it should removed.
https://github.com/olokos/Surftimer-olokos/blob/dev/addons/sourcemod/scripting/SurfTimer.sp#L1880-L1881
https://github.com/olokos/Surftimer-olokos/blob/dev/addons/sourcemod/scripting/SurfTimer.sp#L2122-L2123

**Comment by olokos** [comment] 2020-05-06 23:58
![Bug picture](https://image.prntscr.com/image/Lg2qL46LSBih2SJ6ceG9PA.png)
Still happens on dev branch and threadedSQL aswell, even after building up to 3febe60 commit

**Comment by Bara** [comment] 2020-05-10 14:51
@c0rp3n 
https://github.com/olokos/Surftimer-olokos/blob/dev/addons/sourcemod/scripting/surftimer/timer.sp#L370
Color should be removed, but is still there.

**Comment by c0rp3n** [comment] 2020-05-10 15:05
You need to use `CRemoveTags` here not `CRemoveColors` as this removes color escape codes from a message not the actual tags.

**Comment by CustomStats** [comment] 2020-05-10 23:05
This is now fixed on the scoreboard and through !colors, but still shows the tags when using the !ranks command.

**Comment by Bara** [comment] 2020-05-10 23:15
@CustomStats should be fixed too

**Comment by olokos** [comment] 2020-05-11 06:41
![Still same problem](https://image.prntscr.com/image/2E1dId-PTMGYFNcoNL1teQ.png)
Freshly built dev branch, I will update version number to 285.5 for now, as there are quite some changes in already.

**Comment by Caaine** [comment] 2020-05-11 11:08
increase the MAX_MESSAGE_LENGTH in colorlib.inc to 512 and it's working with the chat

**Comment by olokos** [comment] 2020-05-11 11:28
@Caaine 
Hop on `connect kiepownica.pl` and tell me if it's working now please, just compiled with the change you mentioned.

**Comment by qawery-just-sad** [comment] 2020-05-11 11:35
fixed 
![image](https://user-images.githubusercontent.com/53490397/81557451-4aed6d80-938c-11ea-8ab0-377b0ee02442.png)

**Comment by olokos** [comment] 2020-05-11 11:36
@Bara 
Could you adjust the workflow so it would compile colorlibs.inc with that change aswell?

**Comment by Bara** [comment] 2020-05-11 11:37
that's [already changed](https://github.com/c0rp3n/colorlib-sm/commit/d86ab3eb552bb8792908525c68261cadc6427a32). for releases we always use the default includes without any custom stuff, to keep it reproducable. 👍

**Comment by olokos** [comment] 2020-05-11 12:45
Marvellous, I will update my includes from the repo then!

**Closed by olokos** 2020-05-11 12:45 UTC
Labels: 286, bug
